name: Repsitory dispatch workflow from docs-tidb-operator-release-1.1

on:
  push:
    branches:
      - release-1.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1.1.1
      with:
          token: ${{ secrets.PR_TRIGGER_BUILD_TOKEN }}
          repository: Ti-FE/website-docs/
          event-type: triggered
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repo": "${{ github.repository }}"}'
